general:
  rsu_radius: 1000
  num_rsus: 10
  grid_size: 9

sumo_interface:
  xml_parser:
    path_to_fcd_xml: ./data/fcd_files/Test/sumoTrace.xml
    path_to_net_xml_zip: ./data/net_files/Test/osm.net.xml.gz

garsud:
  deployment_csv: rsu_deployment_garsud.csv
  deployment_parquet: rsu_deployment_garsud.parquet
  num_generations: 10
  num_parents_mating: 5
  sol_per_pop: 20
  mutation_percent_genes: 10

pmcp_b:

branch_and_bound:
  deployment_csv: rsu_deployment_b&b.csv
  deployment_parquet: rsu_deployment_b&b.parquet

