Algorithms:
  AllJunctions:
    run: false
    track_exec_time: false
  BranchAndBound:
    run: false
    track_exec_time: false
  DensityBased:
    run: false
    track_exec_time: true
  GARSUD:
    keep_parents: 10
    num_generations: 40
    num_parents_mating: 10
    optimization_param:
      avg_distance: false
      coverage: true
    run: true
    sol_per_pop: 20
    track_exec_time: true
  PMCP_B:
    run: false
    track_exec_time: true
General:
  base_path: /Users/rouvenrischert
  grid_size: 100
  num_rsus: 700
  plot_map_path: /rsudeploysimcomp/Plots/DeploymentMaps
  rsu_radius: 75
  rsudeploysimcomp_path: /Projects/Python/rsudeploysimcomp
  track_exec_time: true
Plotter:
  run_plot_deployment_map: false
RadiusGridsizeMapping:
  75:
  - 100
  100:
  - 70
  200:
  - 36
SUMOInterface:
  xml_parser:
    path_to_fcd_xml: ./data/fcd_files/Test/sumoTrace.xml
    path_to_net_xml_zip: ./data/net_files/Test/osm.net.xml.gz
VanetInterface:
  configs_path: /Workspace/configs
  deployment_csv_path: /positions/rsu_deployment.csv
  deployment_parquet_path: /positions/rsu_deployment.parquet
  disolv_path: /Projects/Rust/disolv
  fcd_parquet: /positions/koln_fcd.parquet
  input_path: /Workspace/input
  output_path: /Workspace/output
  prep_disolv_path: /Projects/Python/prep-disolv
  raw_path: /Workspace/raw
  scenario: /koln
  track_execution_time: true
